language: node_js
node_js:
- '0.12'
- '0.11'
- '0.10'
before_install:
- cp ci/travis-ci.sh $HOME/
- chmod +x $HOME/travis-ci.sh
- cp ci/npm-config.sh $HOME/
- chmod +x $HOME/npm-config.sh
- $HOME/travis-ci.sh before-install
before_script:
- $HOME/travis-ci.sh before-script
script:
- $HOME/travis-ci.sh script
after_script:
- $HOME/travis-ci.sh after-script
after_success:
- $HOME/travis-ci.sh after-success
before_deploy:
- $HOME/travis-ci.sh before-deploy
- cd built
after_deploy:
- $HOME/travis-ci.sh after-deploy
cache:
  directories:
  - node_modules
notifications:
  irc:
  - chat.freenode.net#kalabox
  email:
    recipients:
    - mike@kalamuna.com
    - ben@kalamuna.com
    on_success: always
env:
  global:
  - secure: pfNK5U/NxT/U/b+udQiDyY9ZgWPNyJ5pUPr0jomQ8qaogQ36sf60LUL8CEIVe5ci3YRaX0K+2OExVg+VOWD/s5ZNSqQoOKNghJZI2aykm0XdS0KVJ6hRk/rktIYM5dNrEMB26byzvCsJIgbKN4WZWGlH3otMPYOCO3Nd5aAqvL8=
  - secure: GWvBFfS9mf64GvoIz9kjyjgTc+NGLNTf05sgOwKMik0Yrk4rbfVANw0RbtPL/gj3jUf3wb/NVPqtN/L5bastzO0Um7Llnz3+ZVXEkyKMA0Kd7MP/tZo7BCsM9rL9Yk0E+cXI7pXtqDMhFCBH2+eSwrAakkr1d3f+LB1ZT5c+6pc=
  - secure: JT53BkQBjlr6UDpVjjmvYODy+NUvw//Z/ymG3Hl7lCWueWLHI8y+VmsOC7cgqUxFFJYXL7N+IiXIo0AKTQHs+VEXB7uSwWDlym4EPU1icgboXMYfYSkMmXNS3eJ4HktIT/OYONFkc1fFBGrpPGh+R8OL+mB5CKDbqXHRJuZe6a0=
