#!/bin/sh

# We need to do this for SSH add now as well
if [ -f "/ssh/.ssh/${SSH_KEY}" ]; then
  eval `ssh-agent -s` > /dev/null
  ssh-add /ssh/.ssh/${SSH_KEY} > /dev/null
fi

if [ "$EVAL" = true ]; then
  eval rsync "$@"
else
  rsync "$@"
fi
